### ISSUE TITLE
Permission Admin

### ISSUE THREAD

**Issue by bijkent** [nouish/EzChestShop#28]
How to give admin permissions for the /ecsadmin remove command?
So players in the Admin group can use the /ecsadmin remove command.
I can't find this permission.

**Comment by Skullians** [comment]
https://github.com/nouish/EzChestShop/blob/main/core/src/main/java/me/deadlight/ezchestshop/commands/EcsAdmin.java#L79
appears to be `ecs.admin(.remove/.reload/etc)`

**Comment by bijkent** [comment]
Thank you so much!
The permission " ecs.admin.remove " worked for the Admin group. 
Сommand  " /ecsadmin remove " is now working.

**Comment by Skullians** [comment]
@nouish close owo
